# Generated by Django 5.2.5 on 2025-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Football Boots'), ('ball', 'Football'), ('goalkeeper_gear', 'Goalkeeper Gear'), ('accessories', 'Accessories')], default='boots', max_length=20),
        ),
    ]
